#+STARTUP: noindent showall
#+OPTIONS: toc:nil date:nil author:nil
#+LATEX_HEADER: \documentclass[12pt]{article}
#+LATEX_HEADER: \usepackage[letterpaper]{geometry}
#+LATEX_HEADER: \usepackage{times}
#+LATEX_HEADER: \geometry{top=1.0in, bottom=1.0in, left=1.0in, right=1.0in}
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \doublespacing
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \lhead{} 
#+LATEX_HEADER: \chead{} 
#+LATEX_HEADER: \rhead{Saleem \thepage} 
#+LATEX_HEADER: \lfoot{} 
#+LATEX_HEADER: \cfoot{} 
#+LATEX_HEADER: \rfoot{} 
#+LATEX_HEADER: \renewcommand{\headrulewidth}{0pt} 
#+LATEX_HEADER: \renewcommand{\footrulewidth}{0pt} 
#+LATEX_HEADER: \setlength\headsep{0.333in}
#+LATEX_HEADER: \newcommand{\bibent}{\noindent \hangindent 40pt}
#+LATEX_HEADER: \newenvironment{workscited}{\newpage \begin{center} Works Cited \end{center}}{\newpage }
#+BEGIN_LATEX
\begin{flushleft}
Khayyam Saleem

Professor Susan Levin

HLI 114 -- Western Literature: Middle Ages to the Present

30 April 2019
\end{flushleft}
#+END_LATEX



#+BEGIN_CENTER
Dante's Superiority Complex in /The Inferno/
#+END_CENTER


#+BEGIN_LATEX
\setlength{\parindent}{0.5in}
#+END_LATEX

#+BEGIN_COMMENT
start paper here
#+END_COMMENT

In Dante Alighieri's /The Inferno of Dante/, we are able to see Dante's development as he descends through the layers of the underworld.


#+BEGIN_COMMENT
end paper here
#+END_COMMENT


#+BEGIN_LATEX
\begin{workscited}

\bibent
Allen, R.L. \textit{The American Farm Book; or Compend of Ameri can Agriculture; Being a Practical Treatise on Soils, Manures, Draining, Irrigation, Grasses, Grain, Roots, Fruits, Cotton, Tobacco, Sugar Cane, Rice, and Every Staple Product of the United States with the Best Methods of Planting, Cultivating, and Prep aration for Market.} New York: Saxton, 1849. Print.

\bibent
Baker, Gladys L., Wayne D. Rasmussen, Vivian Wiser, and Jane M. Porter. \textit{Century of Service: The First 100 Years of the United States Department of Agriculture.}[Federal Government], 1996. Print.

\bibent
Danhof, Clarence H. \textit{Change in Agriculture: The Northern United States, 1820-1870.} Cambridge: Harvard UP, 1969. Print.


\end{workscited}
#+END_LATEX
