#+TITLE: The portrayal of women in Yvain and in Niebelungenlied
#+SUBTITLE: HLI 114 -- Western Literature: Middle Ages to the Present
#+DATE: 14 March 2019
#+OPTIONS: num:nil toc:nil

In both Chretien's Yvain and The Niebelundenlied, we observe two different representations of women and their place in the societies detailed in the stories. The primary female representative in Yvain was Lunete, advisor to Laudine and the catalyst of Yvain's relationship with her. In The Nibelungenlied, Kriemhild is the woman of focus, who takes charge of the wrong done upon her and avenges the death of her husband. Though these two depictions of women contrast significantly, both effectively convey a powerful image of women and their roles in a time and culture that did not work exceptionally hard to empower them.

We can first examine Kriemhild from The Nibelungenlied, arguably the central character for the latter half of the tale. Her character arc is of particular interest, owing to her introduction to the reader as a gentle princess and object of courtship, followed by her development into a ruthless and vengeful femme fatale. We can see this transformation as the author's means of conveying her empowerment. Rather than playing the victim, she employs her sexuality, wit, and sheer mercilessness to deliver unto Gunther and Hagen their just deserts.
